// Brand favicon — generated by next/og. Replaces the default Next.js
// favicon.ico. Renders a lime rounded square with the project's Q
// monogram (matching components/Ornament.tsx) inscribed in ink.
//
// Next 16 picks this up automatically for the route segment.

import { ImageResponse } from "next/og";

export const size = { width: 32, height: 32 };
export const contentType = "image/png";

export default function Icon() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          background: "#c5f500",
          borderRadius: 6,
        }}
      >
        <svg
          width="22"
          height="22"
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <circle cx="10" cy="12" r="3.8" stroke="#0a0a0c" strokeWidth="2.2" />
          <path
            d="M12.4 14.6L15.4 17.8"
            stroke="#0a0a0c"
            strokeWidth="2.2"
            strokeLinecap="round"
          />
        </svg>
      </div>
    ),
    size,
  );
}
