// Open Graph image — 1200x630, generated by next/og.
// Picked up automatically by Next 16 for og:image and twitter:image.
//
// Composition: ink background, faint lime glow at the bottom edge,
// brand mark + wordmark + tagline + small "v1.0 · phase vii" caption.
// No external font fetched — relies on satori's built-in default so
// the build stays hermetic.

import { ImageResponse } from "next/og";

export const size = { width: 1200, height: 630 };
export const contentType = "image/png";
export const alt = "Querymancer — Natural language to SQL";

export default function OpenGraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          background: "#0a0a0c",
          color: "#fafafa",
          position: "relative",
          padding: "72px 80px",
          fontFamily: "sans-serif",
        }}
      >
        {/* Bottom-edge lime glow */}
        <div
          style={{
            position: "absolute",
            left: 0,
            right: 0,
            bottom: 0,
            height: "320px",
            background:
              "radial-gradient(ellipse at center bottom, rgba(197,245,0,0.18), rgba(197,245,0,0) 70%)",
          }}
        />

        {/* Top eyebrow */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 14,
            fontSize: 22,
            color: "#a1a1aa",
            letterSpacing: "0.22em",
            textTransform: "uppercase",
          }}
        >
          <div
            style={{
              width: 36,
              height: 2,
              background: "#c5f500",
            }}
          />
          natural language → sql
        </div>

        {/* Body — mark + wordmark */}
        <div
          style={{
            marginTop: "auto",
            display: "flex",
            alignItems: "center",
            gap: 36,
          }}
        >
          {/* Mark */}
          <div
            style={{
              width: 120,
              height: 120,
              borderRadius: 22,
              background: "#c5f500",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              boxShadow: "0 12px 60px rgba(197,245,0,0.35)",
            }}
          >
            <svg
              width="74"
              height="74"
              viewBox="0 0 24 24"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <circle cx="10" cy="12" r="3.6" stroke="#0a0a0c" strokeWidth="2" />
              <path
                d="M12.4 14.6L15.4 17.8"
                stroke="#0a0a0c"
                strokeWidth="2"
                strokeLinecap="round"
              />
            </svg>
          </div>

          {/* Wordmark + tagline */}
          <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
            <div
              style={{
                display: "flex",
                fontSize: 124,
                fontWeight: 600,
                letterSpacing: "-0.035em",
                lineHeight: 1,
                color: "#fafafa",
              }}
            >
              <span>Querymancer</span>
              <span style={{ color: "#c5f500" }}>.</span>
            </div>
            <div
              style={{
                fontSize: 30,
                color: "#a1a1aa",
                letterSpacing: "-0.01em",
              }}
            >
              Ask your database in plain English.
            </div>
          </div>
        </div>

        {/* Footer line */}
        <div
          style={{
            marginTop: 48,
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            fontSize: 18,
            color: "#71717a",
            letterSpacing: "0.18em",
            textTransform: "uppercase",
            fontFamily: "monospace",
          }}
        >
          <span>schema rag · gemini · safe sql</span>
          <span style={{ color: "#c5f500" }}>v1.0 · phase vii</span>
        </div>
      </div>
    ),
    size,
  );
}
